// Begin Patch Upstream Jan 16, 2017
#include "configure.h"
//compile_stubs.h generated by xcode to dump compile_subs to a string.
//here we fake one.
static const char *compile_stubs ="Empty"; 
// End Patch Upstream Jan 16, 2017

